// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";

import { SimpleNFT$Type } from "./SimpleNFT";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["SimpleNFT"]: SimpleNFT$Type;
    ["contracts/SimpleNFT.sol:SimpleNFT"]: SimpleNFT$Type;
  }
}
