// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";

import { Counters$Type } from "./Counters";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["Counters"]: Counters$Type;
    ["@openzeppelin/contracts/utils/Counters.sol:Counters"]: Counters$Type;
  }
}
