// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import type { Address } from "viem";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";
import "@nomicfoundation/hardhat-viem/types";

export interface Counters$Type {
  "_format": "hh-sol-artifact-1",
  "contractName": "Counters",
  "sourceName": "@openzeppelin/contracts/utils/Counters.sol",
  "abi": [],
  "bytecode": "0x60566050600b82828239805160001a6073146043577f4e487b7100000000000000000000000000000000000000000000000000000000600052600060045260246000fd5b30600052607381538281f3fe73000000000000000000000000000000000000000030146080604052600080fdfea2646970667358221220f4830d7f86e1ab2f8303d17696b97e631053fd399cf240c2d50ef4c88fdba17564736f6c63430008130033",
  "deployedBytecode": "0x73000000000000000000000000000000000000000030146080604052600080fdfea2646970667358221220f4830d7f86e1ab2f8303d17696b97e631053fd399cf240c2d50ef4c88fdba17564736f6c63430008130033",
  "linkReferences": {},
  "deployedLinkReferences": {}
}

declare module "@nomicfoundation/hardhat-viem/types" {
  export function deployContract(
    contractName: "Counters",
    constructorArgs?: [],
    config?: DeployContractConfig
  ): Promise<GetContractReturnType<Counters$Type["abi"]>>;
  export function deployContract(
    contractName: "@openzeppelin/contracts/utils/Counters.sol:Counters",
    constructorArgs?: [],
    config?: DeployContractConfig
  ): Promise<GetContractReturnType<Counters$Type["abi"]>>;

  export function sendDeploymentTransaction(
    contractName: "Counters",
    constructorArgs?: [],
    config?: SendDeploymentTransactionConfig
  ): Promise<{
    contract: GetContractReturnType<Counters$Type["abi"]>;
    deploymentTransaction: GetTransactionReturnType;
  }>;
  export function sendDeploymentTransaction(
    contractName: "@openzeppelin/contracts/utils/Counters.sol:Counters",
    constructorArgs?: [],
    config?: SendDeploymentTransactionConfig
  ): Promise<{
    contract: GetContractReturnType<Counters$Type["abi"]>;
    deploymentTransaction: GetTransactionReturnType;
  }>;

  export function getContractAt(
    contractName: "Counters",
    address: Address,
    config?: GetContractAtConfig
  ): Promise<GetContractReturnType<Counters$Type["abi"]>>;
  export function getContractAt(
    contractName: "@openzeppelin/contracts/utils/Counters.sol:Counters",
    address: Address,
    config?: GetContractAtConfig
  ): Promise<GetContractReturnType<Counters$Type["abi"]>>;
}
